version: '3.8'

services:
  api:
    build: .
    command: python -m libraryapi.app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=bookworm
      - POSTGRES_PASSWORD=my-password
      - POSTGRES_DB=library_db
volumes:
  postgres_data: